#!/bin/bash

REMOTE_VERSION=$(curl -s https://api.github.com/repos/andrewmarklloyd/thermo-pi/commits/master -H "Accept: application/vnd.github.VERSION.sha")

LOCAL_VERSION=$(git rev-parse HEAD)

if [[ ${REMOTE_VERSION} == ${LOCAL_VERSION} ]]; then
  echo 'Software is up to date'
else
  echo 'Software is out of date. Updating now...'
  git pull
  echo 'Installing master-node dependencies...'
  cd ../master-node
  npm install
  echo 'Installing worker-node dependencies...'
  cd ../worker-node
  npm install
  ./kill-processes.sh
  echo 'Starting worker node process...'
  nohup npm start &
fi
